using System;
using System.IO;
using HotDocs.Sdk;

public class TemplateOnDisk : Template, ITemplateOnDisk
{
    public TemplateOnDisk(string fileName, ITemplateLocationOnDisk location, string switches = "", string key = "")
        : base(fileName, switches, key)
    {

    }

    public TemplateOnDisk(PackageTemplateLocation location, string switches = "", string key = "")
        : base(location, switches, key)
    {

    }

    /// <summary>
    /// Returns the full path (based on the directory specified by Location.GetTemplateDirectory) of the template.
    /// </summary>
    /// <returns></returns>
    public string GetFullPath()
    {
        // Note: As the code is currently written, Location will never be null, but in the sake of defensive programming, 
        // we are checking it anyway lest we try to access its members if it were in fact a null object.
        if (Location == null)
            throw new Exception("No location has been specified.");
        return Path.Combine(Location.GetTemplateDirectory(), FileName);
    }

    public ITemplateLocationOnDisk Location { get; private set; }

    /// <summary>
    /// Returns a Template created from a locator string generated by CreateLocator.
    /// </summary>
    /// <param name="locator">A locator string provided by CreateLocator.</param>
    /// <returns></returns>
    public static ITemplateOnDisk Locate(string locator)
    {
        if (string.IsNullOrEmpty(locator))
            throw new ArgumentNullException("locator");

        string decryptedLocator = Util.DecryptString(locator);
        string[] tokens = decryptedLocator.Split('|');
        if (tokens.Length != 4)
            throw new Exception("Invalid template locator.");

        string fileName = tokens[0];
        string switches = tokens[1];
        string key = tokens[2];
        string locationLocator = tokens[3];
        
        //TODO fix this
        //ITemplateOnDisk template = new DiskAccessibleTemplate(fileName, TemplateLocationSerializer.Locate(locationLocator), switches);
        ITemplateOnDisk template = null;
        template.Key = key;
        template.UpdateFileName();
        return template;
    }
}